//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreadorDeFormatos.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CreadorDeFormatos.Languages.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format Creator.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report generation complete!.
        /// </summary>
        public static string ArchiveCompleted {
            get {
                return ResourceManager.GetString("ArchiveCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Reports.
        /// </summary>
        public static string ButtonGenerateFormats {
            get {
                return ResourceManager.GetString("ButtonGenerateFormats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select File.
        /// </summary>
        public static string ButtonSelectExcel {
            get {
                return ResourceManager.GetString("ButtonSelectExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Folder.
        /// </summary>
        public static string ButtonSelectFolder {
            get {
                return ResourceManager.GetString("ButtonSelectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select File.
        /// </summary>
        public static string ButtonSelectFormat {
            get {
                return ResourceManager.GetString("ButtonSelectFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid path, or select a proper file..
        /// </summary>
        public static string InvalidPaths {
            get {
                return ResourceManager.GetString("InvalidPaths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected Date Format.
        /// </summary>
        public static string LabelDateFormat {
            get {
                return ResourceManager.GetString("LabelDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patients Excel.
        /// </summary>
        public static string LabelExcel {
            get {
                return ResourceManager.GetString("LabelExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result Format (DOCX).
        /// </summary>
        public static string LabelFormatDocx {
            get {
                return ResourceManager.GetString("LabelFormatDocx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Folder.
        /// </summary>
        public static string LabelOutputFolder {
            get {
                return ResourceManager.GetString("LabelOutputFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an excel file.
        /// </summary>
        public static string SelectExcelFile {
            get {
                return ResourceManager.GetString("SelectExcelFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Word file.
        /// </summary>
        public static string SelectWordFile {
            get {
                return ResourceManager.GetString("SelectWordFile", resourceCulture);
            }
        }
    }
}
